<?php
/**
 * Created by PhpStorm.
 * User: slava
 * Date: 15.11.15
 * Time: 9:17
 */
namespace frontend\components;
use Yii;
use yii\base\Component;
use yii\base\InvalidCallException;

class NewComponent extends Component
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function test()
    {
        echo 'It i my first component';
    }
}