<?php
/**
 * Created by PhpStorm.
 * User: slava
 * Date: 15.11.15
 * Time: 9:17
 */
namespace frontend\components;
use Yii;
use yii\base\Component;
use yii\base\Event;
use yii\base\InvalidCallException;

class NewComponent extends Component
{
    public $property = "NewComponent property is called<br/>";
    const EVENT_HELLO = 'Model is recieved';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public  function onSomeEvent($event)
    {
        $this->trigger(self::EVENT_HELLO, $event);
    }
}